[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo_mysql"]

[phases.build]
cmds = ["echo 'Build started'", "mkdir -p /var/www/html", "cp -rv . /var/www/html", "echo 'Build complete'"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"
